name: ConsoleName
main: net.obnoxint.mcdev.consolename.ConsoleName
version: 2.4
author: obnoxint
website: http://dev.bukkit.org/bukkit-plugins/consolename
commands:
    bc:
        description: send a broadcast message
        usage: /<command> [message]
    bcc:
        description: send a broadcast message with customized prefix
        usage: /<command> --pre=[prefix] --msg=[message]
    bcset:
        description: (re-)sets the broadcast message prefix either globally or per player
        usage: /<command> ([@player]|[~]) [message]
    bcprop:
        description: set ConsoleName properties
        usage: /<command> [property] [value]